version: '3'

services:

  exemplo:
    build: .
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/app
      - /var/www/app/vendor/

networks:
  default:
    driver: bridge